### ISSUE TITLE
Ensure script performance on .NET Core

### ISSUE THREAD

**Issue by codeape2** [codeape2/netmockery#19]
- Currently no caching of compiled scripts on .NET Core

**Comment by Andrioden** [comment]
@codeape2 - Hello again, here I have a pull request that solves this: https://github.com/codeape2/netmockery/pull/24, any chance you can review and merge this?

**Comment by Andrioden** [comment]
Nevermind, closed the PR, it details in PR.

**Comment by Andrioden** [comment]
@codeape2 - A new PR is up: https://github.com/codeape2/netmockery/pull/25. I decided against caching the compiled scripts, as each takes (now) about 60mb of memory. I see that the code before my net6 refactor cached the last executed script, which is kind of clever, but i decided against it for now.
