### ISSUE TITLE
Upgrade to .net 6

### ISSUE THREAD

**Issue by Andrioden** [codeape2/netmockery#21]
Hei @codeape2 , er du tilgjengelig for å code review og merge endringer av netmockery?

**Comment by Andrioden** [comment]
Klar for review: https://github.com/codeape2/netmockery/pull/22

**Comment by codeape2** [comment]
Ja det kan jeg gjerne, jeg skal se over endringene. Jeg er ikke så inne i hva som har skjedd i .NET-land i de siste årene. Men hvis jeg har forstått det riktig så er gamle ".NET Framework" ikke lenger så aktuelt å bruke, og det er ".NET" (tidligere .NET Core) som er tingen?

**Comment by Andrioden** [comment]
Supert

> Men hvis jeg har forstått det riktig så er gamle ".NET Framework" ikke lenger så aktuelt å bruke, og det er ".NET" (tidligere .NET Core) som er tingen?

Riktig. 

.NET Framework bør tenkes på som legacy nå.

Jau, nå er det navngitt .net 5, .net 6, .net 7, osv. Ved overgangen fra .net core 3 -> net 5 endret man navn, uten nevneverdige tekniske endringer

**Comment by Andrioden** [comment]
@codeape2 - Kan du ta en ny titt? En del endringer gjort. 🙏

**Comment by codeape2** [comment]
@Andrioden jeg ser på det ila. helga.

**Comment by Andrioden** [comment]
@codeape2 - Klart igjen

PRn er åpentbart ikke perfekt, men dette bør holde for denne runden som handler om å løfte til .net6. Om det dukker opp følgefeil ift nhn så vil vi ta tak i det.

**Comment by Andrioden** [comment]
@codeape2 - Takk for tiden. Jeg lukker denne.

To oppfølgingstasks:
- https://github.com/codeape2/netmockery/issues/23
- https://github.com/codeape2/netmockery/issues/19

Mens jeg kanskje har deg her, er det aktuelt og sette meg som Collaborator på prosjektet?
